language: erlang
env:
  - ELIXIR_VER=v0.14.2
otp_release:
  - 17.0
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/$ELIXIR_VER/Precompiled.zip && unzip -qq Precompiled.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
before_script:
    - mix local.install http://s3.hex.pm/installs/hex.ez --force
    - mix deps.get
script: 
    - mix test
